config/urls.py
from django.contrib import admin
from django.urls import path

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
]

website/urls.py
#  website/urls.py

from django.shortcuts import render
from django.urls import path

from . import views

app_name = "website"

urlpatterns = [
    path('', views.home_page_view, name='home'),
    path('segundo', views.segundo_page_view, name='segundo'),
    path('terceiro', views.terceiro_page_view, name='terceiro'),
    path('layouts', views.layouts_page_view, name='layouts'),
    path('multimedia', views.multimedia_page_view, name='multimedia'),
    path('inventario', views.inventario_page_view, name='inventario'),
    path('tecnicas', views.tecnicas_page_view, name='tecnicas')

]

website/models.py
from django.db import models

# Create your models here.

website/views.py
# Create your views here.
from django.shortcuts import render
from . import views
import datetime

app_name = "website"


def home_page_view(request):
    return render(request, 'website/home.html')


def segundo_page_view(request):
    return render(request, 'website/segundo.html')


def terceiro_page_view(request):
    return render(request, 'website/terceiro.html')

def layouts_page_view(request):
    return render(request, 'website/layouts.html')

def multimedia_page_view(request):
    return render(request, 'website/multimedia.html')

def inventario_page_view(request):
    return render(request, 'website/inventario.html')

def tecnicas_page_view(request):
    return render(request, 'website/tecnicas.html')

website/templates/website/base.html
<!DOCTYPE html>
{% load static %}
<html lang="pt">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
    content="width=device-width,
    initial-scale=1.0">
    <meta charset="UTF-8">
    <meta name="author" content="Duarte Cambra">
    <meta name="keywords" content="php">
    <meta name="description" content="Projeto Parte 2">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Source+Code+Pro&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Dela+Gothic+One&display=swap" rel="stylesheet">
    {% load static %}
    <link rel="stylesheet" href="{% static 'website/css/base2.css' %}">
    <title>Projeto PW</title>
</head>
<body>
    <header class="jumbotron text-center">
        <nav>
          <a href="{% url 'website:home' %}" class="btn btn-info">Home</a>
          <a href="{% url 'website:layouts' %}" class="btn btn-info">Layouts</a>
          <a href="{% url 'website:multimedia' %}" class="btn btn-info">Multimedia</a>
          <a href="{% url 'website:inventario' %}" class="btn btn-info">Inventário</a>
          <a href="{% url 'website:tecnicas' %}" class="btn btn-info">Técnicas usadas</a>
        </nav>
    </header>

    <article class="container">
        <main class="col-sm-6">
            {% block main %}
            {% endblock main %}
        </main>
        <aside class="col-sm-6">
            {% load static %}
            <img src="{% static 'website/images/image.png' %}">
            <a href="https://www.topgadget.com.br/howto/sites-e-web/como-adicionar-um-atributo-a-uma-tag-html.htm"><figure class="figure"><img src="{% static 'website/images/html-css-js-1.jpg' %}"<></figure></a>
            <a href="https://brytdesigns.com/html-css-javascript-whats-the-difference/"><figure class="figure"><img src="{% static 'website/images/html_css_javascript_infographic.png' %}""images/html_css_javascript_infographic.png"<></figure></a>
            <a href="https://pplware.sapo.pt/tutoriais/programacao-web-1-introducao/"><figure class="figure"><img src="{% static 'website/images/wordcloud.png' %}"<></figure></a>
        </aside>
    </article>
    <footer>Programação Web, Universidade Lusófona de Humanidades e Tecnologias, 2020/2021</footer>

    
</body>
</html>

website/templates/website/baseBackup.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Django / Python</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    {% load static %}
    <link rel="stylesheet" href="{% static 'website/css/base.css' %}">
</head>

<body>
    <header class="jumbotron text-center">
        <h1>Website usando Django</h1>
        <p>Django é um framework para desenvolvimento rápido para web, escrito em Python, que utiliza o padrão model-template-view. </p>
        <nav>
            <a href="{% url 'website:home' %}" class="btn btn-info">Home</a>
            <a href="{% url 'website:segundo' %}" class="btn btn-info">Django</a>
            <a href="{% url 'website:terceiro' %}" class="btn btn-info">Python</a>
        </nav>
    </header>
    <article class="container">
        <main class="col-sm-6">
            {% block main %}
            {% endblock main %}
        </main>
        <aside class="col-sm-6">
            {% load static %}
            <img src=cc>
        </aside>
    </article>
    <footer><p>Trabalho realizado para Programação Web</p></footer>
</body>
</html>

website/templates/website/home.html
{% extends 'website/base.html' %}

{% block main %}
    <h3>Home</h3>

    <p>Esta é a home page do website realizado em Django. O layout do website não muda quando acede às diferentes páginas, a única coisa que altera é o conteúdo do main.</p>

    <article>
        <p>Na Unidade Curricular de <a href="https://secure.grupolusofona.pt/ulht/moodle/course/view.php?id=38119"><i>Programação Web</i></a>, dada na <a href="https://www.ulusofona.pt/">Universidade Lusófona</a> fomos desafiados a elaborar um website para a parte 1 do <i>Projeto</i> seguindo uma <a href="https://github.com/ULHT-PW-2020-21/pw-projeto-fase1">lista de requisitos</a>.</p>
        <p>O conteúdo aprendido nesta UC até à data foi:</p>
        <ul>
            <li>Funcionamento da Web</li>
            <li>Tecnologias, paradigmas e padrões de desenho da Web</li>
            <li>HTML e seus elementos para estruturação de conteúdos multimédia</li>
            <li>Formulários para envio de dados</li>
            <li>Formulários para envio de dados</li>
            <li>SVG para gráficos vetoriais escaláveis</li>
            <li>HTML5 e elementos semânticos</li>
            <li>CSS e seus seletores, para estilização de conteúdos</li>
            <li>Propriedades CSS</li>
            <li>Design responsivo layouts dinâmicos</li>
            <li>Layouts CSS flex e CSS grid</li>
            <li>Efeitos e animações CSS</li>
            <li>Menus dropdown</li>
            <li>Cor</li>
        </ul>

        <p>Ao explorar o website vai poder observar o que foi aprendido nesta cadeira, aplicado na prática.</p>
    </article>  

{% endblock %}

website/templates/website/inventario.html
{% extends 'website/base.html' %}

{% block main %}
<article>
    <h1>Técnicas usadas</h1>

    <p> As etiquetas HTML5 semânticas usadas, seletores e propriedades CSS, media queries, tipos de display usados, animações e efeitos usados neste projeto serão descritos na tabela abaixo.</p>

    <table cellspacing="1" cellpadding="1" border="2" bgcolor="gray" align="center">

        <caption>
            Tabela de Inventário
        </caption>
        <colgroup>
            <col align="left" span="1">
            <col align="left" span="1">
            <col align="left" span="1">
        </colgroup>
        
        <tr>
            <th>Páginas</th>
            <td>5</td>
        </tr>
        <tr>
            <th>Imagens</th>
            <td>17</td>
        </tr>
        <tr>
            <th>Links Externos</th>
            <td>12</td>
        </tr>
        <tr>
            <th>Vídeos</th>
            <td>1</td>
        </tr>
        <tr>
            <th>Animações</th>
            <td>1</td>
        </tr>

    </table>

</article> 
{% endblock %}

website/templates/website/layouts.html
{% extends 'website/base.html' %}

{% block main %}
<article>
    <h1>Layouts</h1>

    <p> A maneira como o conteúdo é apresentado ao utilizador é muito importante. É uma parte fundamental da comunicação visual e do desafio que é desenvolver um website. Um layout bem desenhado torna a 
        informação rápida de ser consumida e apelativa aos olhos de quem o vê.</p>

    <h2>Abaixo vamos ver os tipos de layouts mais usados:</h2>

    <h2>1. One-Column Layout</h2>
    <p>É o mais simple dos layouts, organiza informação em apenas uma coluna. O conteúdo é facil de seguir e é o layout perfeito para dispositivos com uma tela reduzida (ex: smartphone).</p>
    <figure>
        {% load static %}
        <img src="{% static 'website/images/one-column-layout.png' %}"<>
        <figcaption>One-Column Layout. </figcaption>
        <details>A fotografia foi retirada <a href="https://www.homeandlearn.co.uk/WD/wds6p4.html">daqui</a></details>
    </figure>

    <h2>2. Two-Column Layout</h2>
    <p>É dos layouts mais simples no entanto muito útil, organiza informação em duas colunas. É especialmente útil se queremos repetir uma certa coluna em todas as páginas (ex: barra de navegação).</p>
    <figure>
        {% load static %}
        <img src="{% static 'website/images/two-columns-layout.png' %}"<>
        <figcaption>Two-Column Layout.</figcaption>
        <details>A fotografia foi retirada <a href="https://vanseodesign.com/css/2-column-layout-code/">daqui</a></details>
    </figure>

    <h2>3. A grid of cards</h2>
    <p>É um layout que é apresentado como uma grelha de conteúdos clicáveis. É especialmente útil para websites com muito conteúdo que tenha o mesmo valor de importância (ex: YouTube).</p>
    <figure>
        {% load static %}
        <img src="{% static 'website/images/youtube2.jpg' %}"<>
        <figcaption>Grid of Carts Layout.</figcaption>
        <details>A fotografia foi retirada <a href="htttps://youtube.com">daqui</a></details>

    </figure>
</article>
{% endblock %}

website/templates/website/multimedia.html
{% extends 'website/base.html' %}

{% block main %}
<article >
    <div class="flex-container">
        <figure>
            {% load static %}
            <img src="{% static 'website/images/website1.jpg' %}"<>
            <figcaption>Fotografia retirada <a href="https://www.awwwards.com/95-inspiring-websites-of-web-design-agencies.html">daqui</a>.</figcaption>
        </figure>

        <figure>
            {% load static %}
            <img src="{% static 'website/images/website2.jpg' %}" >
            <figcaption>Fotografia retirada <a href="https://www.brightdesign.co.uk/5-of-the-best-website-designs-according-to-the-internet">daqui</a>.</figcaption>
        </figure>

        <figure>
            {% load static %}
            <img src="{% static 'website/images/website5.jpg' %}" >
            <figcaption>Fotografia retirada <a href="https://xd.adobe.com/ideas/principles/web-design/11-website-layouts-that-made-content-shine-in-2019/">daqui</a>.</figcaption>
        </figure>

        <figure>
            {% load static %}
            <img src="{% static 'website/images/website3.jpg' %}" >
            <figcaption>Fotografia retirada <a href="https://www.brightdesign.co.uk/5-of-the-best-website-designs-according-to-the-internet">daqui</a>.</figcaption>
        </figure>

        <figure>
            {% load static %}
            <img src="{% static 'website/images/website4.jpg' %}" >
            <figcaption>Fotografia retirada <a href="https://www.brightdesign.co.uk/5-of-the-best-website-designs-according-to-the-internet">daqui</a>.</figcaption>
        </figure>

        
    </div>

</article>
{% endblock %}

website/templates/website/segundo.html
{% extends 'website/base.html' %}

{% block main %}
    <h3>Django</h3>
    <p>Na Unidade Curricular de Programação Web, dada na Universidade Lusófona fomos desafiados a elaborar um website usando Django.</p>
{% endblock %}

website/templates/website/tecnicas.html
{% extends 'website/base.html' %}

{% block main %}
<article>
    <h1>Técnicas usadas</h1>

    <p> As etiquetas HTML5 semânticas usadas, seletores e propriedades CSS, media queries, tipos de display usados, animações e efeitos usados neste projeto serão descritos na tabela abaixo.</p>

    <table cellspacing="1" cellpadding="1" border="1" bgcolor="white">

        <caption>
            Técnicas usadas
        </caption>
        <colgroup>
            <col align="left" span="1">
            <col align="left" span="1">
            <col align="left" span="1">
        </colgroup>
        
        <tr>
            <th>Características</th>
            <th>Elementos/técnicas</th>
            <th>Exemplos</th>
        </tr>
        <tr>
            <td>Layouts</td>
            <td>Usou-se o CSS grid e CSS flexbox para construção de layouts.</td>
            <td></td>
        </tr>
        <tr>
            <td>Responsividade</td>
            <td>Foram usadas media queries que adaptam o layout para telemovel e PC consoante o tamanho da janela do browser.</td>
            <td></td>
        </tr>
        <tr>
            <td>Seletores</td>
            <td>Foram usados seletores de ...	</td>
            <td>c</td>
        </tr>
        <tr>
            <td>Etiquetas</td>
            <td>HTML5 main, header, article, aside, footer, figure, img, table, figcaption, ul</td>
            <td>c</td>
        </tr>
        <tr>
            <td>Animações</td>
            <td>Foram feitas animações usando keyframes</td>
            <td>c</td>
        </tr>
        <tr>
            <td>Fonte</td>
            <td>Foi usada uma fonte da Google Fonts</td>
            <td>c</td>
        </tr>
        <tr>
            <td>Imagens documentadas</td>
            <td>Todas as imagens estão inseridas dentro de uma etiqueta figcaption, contendo um título e um hiperlink para onde foram retiradas.</td>
            <td>c</td>
        </tr>
        

        <tr>
            <td>a</td>
            <td>b</td>
            <td>c</td>
        </tr>
        

    </table>

</article>
{% endblock %}

website/templates/website/terceiro.html
{% extends 'website/base.html' %}

{% block main %}
    <h3>Python</h3>
    <p>Python é uma linguagem de programação de alto nível, interpretada de script, imperativa, orientada a objetos, funcional, de tipagem dinâmica e forte. Foi lançada por Guido van Rossum em 1991.</p>
  
{% endblock %}